import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {createSession,deserialize,dispatch,step,replay,serialize,newCampaign,recordWin,unlocked,restoreCampaign} from './engine';
import {levels} from './levels';
import {runEpisode} from './solver';
import type {Command} from './engine';
const send=(s:ReturnType<typeof createSession>,command:Command)=>dispatch(s,command).session;
describe('complete renderer-independent game engine',()=>{
 it('imports no graphics, browser, timers, or randomness throughout its dependency graph',()=>{
  const visited=new Set<string>();function visit(file:string){if(visited.has(file))return;visited.add(file);const source=readFileSync(file,'utf8');expect(source).not.toMatch(/\b(window|document|localStorage|requestAnimationFrame|setInterval|setTimeout|performance)\b|Math\.random|from ['"](?:react|three|lucide)/);for(const match of source.matchAll(/from ['"](\.\/[\w/]+)['"]/g))visit(resolve(dirname(file),match[1]+'.ts'));}visit(resolve('src/engine.ts'));expect(visited.size).toBeGreaterThanOrEqual(5);
 });
 it('has one time base for roots, physiology, and deadline rules; batch size does not change outcomes',()=>{
  const initial=send(createSession(),{type:'target',point:{x:-.18,y:-.9}}),snapshot=serialize(initial);let chunks=initial;for(let i=0;i<32;i++)chunks=step(chunks,.375);const large=step(initial,12);expect(serialize(chunks)).toBe(serialize(large));expect(serialize(initial)).toBe(snapshot);expect(large.game.time).toBe(20);expect(large.world.totalLength).toBeGreaterThan(initial.world.totalLength);
 });
 it('preserves fractional time rather than rounding actions into extra simulation time',()=>{let s=createSession();for(let i=0;i<100;i++)s=step(s,.01);expect(s.ticks).toBe(4);expect(s.game.time).toBe(9);expect(s.carryHours).toBeCloseTo(0,8);expect(step(createSession(),.1).game.time).toBe(8);});
 it('rejects illegal moves, doses, species actions, and powered controls centrally',()=>{let s=createSession();const bad:Command[]=[{type:'water',amount:999 as 100},{type:'target',point:{x:9,y:0}},{type:'ventilation',value:1},{type:'lamp',enabled:true},{type:'shade',value:NaN},{type:'switch-tip',index:-1}];for(const c of bad){const r=dispatch(s,c);expect(r.accepted).toBe(false);s=r.session;}expect(s.rejected).toBe(bad.length);expect(s.game.budget).toBe(95);expect(dispatch(createSession('after-sunset'),{type:'prune'}).accepted).toBe(false);expect(dispatch(createSession(),{type:'feed',source:'prey'}).accepted).toBe(false);});
 it('does not let root progress or resource spending continue after a terminal result',()=>{const s=step(createSession(),10000);expect(s.result?.won).toBe(false);expect(step(s,100)).toBe(s);const r=dispatch(s,{type:'water',amount:100});expect(r.accepted).toBe(false);expect(r.session.game.water).toBe(s.game.water);expect(r.session.world).toBe(s.world);});
 it('round-trips a paused running save and rejects damaged root, map, time, and result data',()=>{const s=step(send(createSession(),{type:'target',point:{x:-.18,y:-.9}}),3.1);expect(deserialize(serialize(s))).toEqual(s);for(const alter of [(x:typeof s)=>x.world.active=-1,(x:typeof s)=>x.world.deposits[0].amount=Infinity,(x:typeof s)=>x.game.time=999,(x:typeof s)=>x.world.rocks=[],(x:typeof s)=>x.result={won:true,stars:3,reasons:[]}]){const changed=structuredClone(s);alter(changed);expect(()=>deserialize(serialize(changed))).toThrow();}});
 it.each(levels.map(l=>[l.id]))('can complete %s using only the same command API as the browser',(id)=>{const s=runEpisode(id,19);expect(s.result?.won).toBe(true);expect(s.game.status).toBe('success');expect(s.rejected).toBe(0);expect(s.world.connections).toBeGreaterThanOrEqual(levels.find(l=>l.id===id)!.roots);expect(deserialize(serialize(s))).toEqual(s);const reconstructed=replay(id,19,s.commands,s.ticks);expect(serialize(reconstructed)).toBe(serialize(s));});
 it('requires good decisions on advanced levels: no cooling loses warm nights and no lamp loses the clouded bog',()=>{expect(runEpisode('warm-nights',2,'no-equipment').result?.won).toBe(false);expect(runEpisode('clouded-bog',2,'no-equipment').result?.won).toBe(false);});
 it('makes neglect and repeated flooding fail even when the bad policy explores roots',()=>{for(const id of ['first-roots','after-sunset','hungry-bog']){expect(runEpisode(id,3,'neglect').result?.won).toBe(false);expect(runEpisode(id,3,'overwater').result?.won).toBe(false);}});
 it('unlocks the full campaign through actual wins and records best stars without downgrading',()=>{let c=newCampaign();expect(unlocked(c,levels[1].id)).toBe(false);for(const level of levels){expect(unlocked(c,level.id)).toBe(true);const s=runEpisode(level.id);c=recordWin(c,s);expect(c.best[level.id]).toBeGreaterThan(0);}expect(Object.keys(c.best)).toHaveLength(6);expect(restoreCampaign(JSON.stringify(c))).toEqual(c);expect(restoreCampaign('{')).toEqual(newCampaign());expect(restoreCampaign('{"version":1,"best":{"unknown":99}}')).toEqual(newCampaign());});
});
