import { useEffect, useRef } from 'react';
import { conditions, missionOf, equipmentInfo } from './simulation';
import type { GameState, Layer } from './simulation';
import type { RootWorld } from './rootWorld';
import { getLevel, levels, nextLevel } from './levels';
import { unlocked } from './engine';
import type { Campaign, Session } from './engine';
export type Tool='root'|'water'|'feed'|'shade'|'vent'|'prune';
export type Screen='play'|'brief'|'pause'|'equipment'|'missions'|'guide'|'journal';
export const tools:{id:Tool;name:string;hint:string;glyph:string}[]=[
  {id:'root',name:'GROW ROOTS',hint:'Click a destination in the soil. WASD steers. B branches; Tab switches tips.',glyph:'root'},
  {id:'water',name:'WATER',hint:'Click the soil to apply 100 mL. Water is finite. Wet roots also need air.',glyph:'water'},
  {id:'feed',name:'NUTRIENTS',hint:'Click the soil to supply mineral nitrogen (€12). Adds dissolved salts.',glyph:'feed'},
  {id:'shade',name:'SHADE',hint:'Click the soil to cycle shade: 0%, 20%, 40%. Less heat, less carbon gain.',glyph:'sun'},
  {id:'vent',name:'VENTILATE',hint:'Click the soil to cycle ventilation. Cooling can increase water loss.',glyph:'wind'},
  {id:'prune',name:'PRUNE',hint:'Click the canopy to prune tomato foliage. Removes 12% of biomass.',glyph:'prune'},
];
export interface HudProps {session:Session;campaign:Campaign;state:GameState;world:RootWorld;tool:Tool;screen:Screen;layer:Layer;paused:boolean;speed:number;toast:string;inspect:boolean;complete:boolean;tutorialActive?:boolean}
export interface Hit {action:'tool'|'menu'|'buy'|'species'|'start'|'resume'|'retry'|'next'|'speed'|'pause'|'layer';value?:string}
export function hudHit(x:number,y:number,w:number,h:number,p:HudProps):Hit|null {
  if(p.screen==='brief')return{action:'start'};
  if(p.state.status!=='active'&&p.screen==='play')return{action:p.complete?'next':'retry'};
  if(p.screen==='equipment'){const ew=Math.min(560,w-40),left=w/2-ew/2,top=h/2-165;for(let i=0;i<4;i++)if(x>left&&x<left+ew&&y>top+i*82&&y<top+i*82+74)return{action:'buy',value:equipmentInfo[i].id};if(y>h/2+205)return{action:'resume'};return null;}
  if(p.screen==='missions'){for(const cell of missionCells(w,h))if(x>cell.x&&x<cell.x+cell.w&&y>cell.y&&y<cell.y+cell.h)return{action:'species',value:levels[cell.i].id};if(y>h-50)return{action:'resume'};return null;}
  if(p.screen!=='play'){if(y>h*.7)return{action:'resume'};return null;}
  const tw=Math.min(88,(w-40)/6),left=w/2-tw*3;
  if(y>h-92&&y<h-30&&x>left&&x<left+tw*6)return{action:'tool',value:tools[Math.floor((x-left)/tw)].id};
  if(x>w-152&&y<76)return{action:'pause'};
  if(x>w-90&&y>h-170&&y<h-123)return{action:'menu',value:'equipment'};
  return null;
}
function missionCells(w:number,h:number){const cols=w<620?2:3,rows=6/cols,width=Math.min(810,w-40),height=Math.min(400,h-200),cw=width/cols,ch=height/rows;return levels.map((_,i)=>({i,x:(w-width)/2+i%cols*cw+5,y:(h-height)/2+Math.floor(i/cols)*ch+14,w:cw-10,h:ch-10}));}
export function GameHUD(props:HudProps) {
  const ref=useRef<HTMLCanvasElement>(null),live=useRef(props);live.current=props;
  useEffect(()=>{const canvas=ref.current!,ctx=canvas.getContext('2d')!;let frame=0;const resize=()=>{const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);canvas.width=r.width*dpr;canvas.height=r.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);};const ro=new ResizeObserver(resize);ro.observe(canvas);resize();
    function round(x:number,y:number,w:number,h:number,r=8){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
    function panel(x:number,y:number,w:number,h:number,alpha=.86){ctx.fillStyle=`rgba(24,43,32,${alpha})`;round(x,y,w,h);ctx.fill();ctx.strokeStyle='rgba(206,226,172,.16)';ctx.lineWidth=1;ctx.stroke();}
    function text(t:string,x:number,y:number,size=12,color='#e8efd5',weight=400,align:CanvasTextAlign='left'){ctx.font=`${weight} ${size}px "DM Sans", sans-serif`;ctx.textAlign=align;ctx.fillStyle=color;ctx.fillText(t,x,y);}
    function wrap(t:string,x:number,y:number,max:number,size=12,color='#b5c4a2',line=20){const words=t.split(' ');let row='',offset=0;for(const word of words){const next=row?`${row} ${word}`:word;ctx.font=`400 ${size}px "DM Sans",sans-serif`;if(ctx.measureText(next).width>max&&row){text(row,x,y+offset,size,color);offset+=line;row=word;}else row=next;}if(row)text(row,x,y+offset,size,color);return y+offset+line;}
    function bar(x:number,y:number,w:number,value:number,color:string){ctx.fillStyle='#b4c59a30';round(x,y,w,3,2);ctx.fill();ctx.fillStyle=color;round(x,y,Math.max(0,Math.min(1,value))*w,3,2);ctx.fill();}
    function icon(glyph:string,x:number,y:number,color='#d1e0b5',size=20){ctx.save();ctx.translate(x,y);ctx.scale(size/20,size/20);ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=1.35;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();if(glyph==='water'){ctx.moveTo(0,-9);ctx.bezierCurveTo(-2,-5,-7,0,-7,4);ctx.bezierCurveTo(-7,12,7,12,7,4);ctx.bezierCurveTo(7,0,2,-5,0,-9);}else if(glyph==='root'){ctx.moveTo(0,-9);ctx.lineTo(0,8);ctx.moveTo(0,-2);ctx.lineTo(-6,3);ctx.lineTo(-8,7);ctx.moveTo(0,2);ctx.lineTo(6,5);ctx.moveTo(0,-5);ctx.bezierCurveTo(-9,-13,-9,-3,0,-5);ctx.moveTo(0,-6);ctx.bezierCurveTo(9,-13,9,-3,0,-6);}else if(glyph==='feed'){ctx.moveTo(-3,-9);ctx.lineTo(3,-9);ctx.moveTo(-2,-9);ctx.lineTo(-2,-2);ctx.lineTo(-7,7);ctx.quadraticCurveTo(-7,9,-5,9);ctx.lineTo(5,9);ctx.quadraticCurveTo(7,9,7,7);ctx.lineTo(2,-2);ctx.lineTo(2,-9);ctx.moveTo(-4,3);ctx.lineTo(4,3);}else if(glyph==='sun'){ctx.arc(0,0,4,0,Math.PI*2);for(let a=0;a<8;a++){const angle=a*Math.PI/4;ctx.moveTo(Math.cos(angle)*7,Math.sin(angle)*7);ctx.lineTo(Math.cos(angle)*9,Math.sin(angle)*9);}}else if(glyph==='wind'){ctx.moveTo(-9,-5);ctx.lineTo(3,-5);ctx.bezierCurveTo(9,-5,9,-11,4,-9);ctx.moveTo(-9,0);ctx.lineTo(7,0);ctx.moveTo(-9,5);ctx.lineTo(2,5);ctx.bezierCurveTo(9,5,9,12,4,10);}else{ctx.moveTo(-7,-8);ctx.lineTo(7,8);ctx.moveTo(7,-8);ctx.lineTo(-7,8);ctx.moveTo(-2,6);ctx.arc(-5,8,3,0,Math.PI*2);ctx.moveTo(8,8);ctx.arc(5,8,3,0,Math.PI*2);}ctx.stroke();ctx.restore();}
    let lastPaint=0;const draw=()=>{frame=requestAnimationFrame(draw);const now=performance.now();if(now-lastPaint<1000/30)return;lastPaint=now;const p=live.current,s=p.state,m=missionOf(s),level=getLevel(p.session.levelId),c=conditions(s);const w=canvas.clientWidth,h=canvas.clientHeight,narrow=w<860;ctx.clearRect(0,0,w,h);
      // The HUD belongs to the game world: one small mission strip, supplies, and a tool belt.
      const vignette=ctx.createLinearGradient(0,0,0,h);vignette.addColorStop(0,'rgba(20,37,27,.36)');vignette.addColorStop(.25,'rgba(20,37,27,0)');vignette.addColorStop(.65,'rgba(20,37,27,0)');vignette.addColorStop(1,'rgba(16,32,24,.5)');ctx.fillStyle=vignette;ctx.fillRect(0,0,w,h);
      if(!p.tutorialActive){text('V E R D A N T',28,37,16,'#f2f3de',650);text(`0${level.number}  /  ${m.name.toUpperCase()}`,28,60,9,'#d6ddc3',500);
      if(!narrow){const mx=228;panel(mx,18,286,55,.65);text(level.title.toUpperCase(),mx+14,37,8,'#b8c9a3',550);text(`${s.biomass.toFixed(2)} / ${m.target.toFixed(1)} g   ·   Roots ${p.world.connections}/${level.roots} patches`,mx+14,58,11,'#ebefd6',500);bar(mx+14,66,255,(s.biomass-3.5)/(m.target-3.5),'#b6d392');}
      const rx=w-365;if(!narrow){text(`€ ${s.budget}`,rx,38,14,'#f3e9c3',500);text('GRANT',rx,56,7,'#d2d6b6');text(`${s.water.toFixed(1)} L`,rx+90,38,14,'#d5e7e1',500);text('WATER',rx+90,56,7,'#d2d6b6');text(`${s.energy.toFixed(1)} kWh`,rx+171,38,12,'#e7e5bd',500);text('ENERGY',rx+171,56,7,'#d2d6b6');}
      panel(w-125,17,101,57,.65);text(`DAY ${String(Math.min(m.days,Math.floor(s.time/24)+1)).padStart(2,'0')} / ${m.days}`,w-74,37,10,'#e5eccb',550,'center');text(`${String(Math.floor(s.time%24)).padStart(2,'0')}:${s.time%1>=.5?'30':'00'}  ${p.paused?'Ⅱ':`▶ ${p.speed}×`}`,w-74,58,11,'#bacfa6',450,'center');
      if(narrow){panel(18,83,215,50,.7);text(`${s.biomass.toFixed(2)} / ${m.target} g   ·   Roots ${p.world.connections}/${level.roots}`,30,102,10);text(`€${s.budget}   ·   ${s.water.toFixed(1)} L   ·   ${s.energy.toFixed(1)} kWh`,30,121,9,'#bdcba9');}
      // Compact vital readout, with actual problems called out as game events.
      const bx=28,by=narrow?158:106;text('VITALITY',bx,by,7,'#edf0d5',550);text(`${s.health.toFixed(0)}%`,bx+134,by,10,s.health<60?'#f0b492':'#e1efc5',500,'right');bar(bx,by+9,134,s.health/100,s.health<60?'#d19a75':'#a6c785');text('CARBON RESERVES',bx,by+33,7,'#e3e7c7',550);text(`${Math.max(0,s.carbon).toFixed(2)} g`,bx+134,by+33,10,'#e6d5a3',500,'right');bar(bx,by+42,134,s.carbon/2,'#d4bd7a');
      if(p.inspect){panel(w-230,100,204,220,.88);text('SPECIMEN READINGS',w-214,124,9,'#d9e4c0',550);const readings=[['Temperature',`${c.temperature.toFixed(1)} °C`],['Humidity',`${Math.round(c.humidity*100)}%`],['Light',`${Math.round(c.ppfd)} µmol/m²/s`],['VPD',`${c.vpd.toFixed(2)} kPa`],['Soil saturation',s.equipment.includes('sensor')?`${Math.round(s.moisture*100)}%`:s.moisture>.6?'Wet':s.moisture>.3?'Moist':'Dry'],['Available nitrogen',`${s.nitrogen.toFixed(0)} mg`],['Root air',s.equipment.includes('sensor')?`${Math.round(c.oxygen*100)}% index`:c.oxygen>.7?'Available':'Restricted'],['Dissolved salt index',s.equipment.includes('sensor')?s.salinity.toFixed(2):'Probe required']];readings.forEach(([label,value],i)=>{text(label,w-214,150+i*20,9,'#b2c29c');text(value,w-42,150+i*20,9,'#edf0d6',500,'right');});}
      if(c.heatwave&&s.status==='active'){const y=narrow?218:92;panel(w/2-119,y,238,32,.8);icon('sun',w/2-96,y+16,'#e7c381',14);text('HEATWAVE  ·  WATCH WATER DEMAND',w/2-77,y+20,8,'#e8d3a1',500);}
      if(p.paused&&p.screen==='play'&&s.status==='active'){const y=narrow?211:105;text('TIME PAUSED',w/2,y,9,'#f1f0d5',600,'center');text('P to resume',w/2,y+17,8,'#d8dfc1',400,'center');}
      }
      const tw=Math.min(88,(w-40)/6),left=w/2-tw*3;panel(left-5,h-97,tw*6+10,69,.9);tools.forEach((t,i)=>{const x=left+i*tw,selected=t.id===p.tool;if(selected){ctx.fillStyle='#abc78d25';round(x+2,h-93,tw-4,59,5);ctx.fill();ctx.strokeStyle='#b4cc8a88';ctx.stroke();}text(`${i+1}`,x+9,h-80,10,selected?'#d4e6b7':'#91a782',550);icon(t.glyph,x+tw/2,h-68,selected?'#e4edc8':'#94ac86',18);text(t.id==='feed'&&s.species==='flytrap'?'PREY':narrow?t.name.split(' ')[0]:t.name,x+tw/2,h-42,narrow?8:9,selected?'#dee8bd':'#a1b594',500,'center');});
      const selected=tools.find(t=>t.id===p.tool)!;text(p.tool==='feed'&&s.species==='flytrap'?'Click a trap to supply prey (€8). Insects supply minerals; sunlight supplies energy.':narrow?'WASD / CLICK TO GROW  ·  SELECT A TOOL BELOW':selected.hint,w/2,h-14,narrow?7:9,'#d9e2c4',400,'center');
      if(!narrow&&!p.tutorialActive){text('B  BRANCH    TAB  SWITCH TIP    F  SCIENCE VIEW',28,h-151,8,'#d6dfc5');text('P  PAUSE    E  EQUIPMENT    M  MISSIONS    H  GUIDE    T  TRAINING',28,h-131,8,'#d6dfc5');text(`${(p.world.totalLength*10).toFixed(0)} cm · ${p.world.paths.length} root tips`,28,h-177,10,'#e2e6c5',500);}
      panel(w-75,h-171,50,38,.7);text('E',w-50,h-154,12,'#e3ebc9',600,'center');text('GEAR',w-50,h-140,6,'#bfceaa',500,'center');
      if(p.layer!=='natural'){text(p.layer==='water'?'WATER & MINERAL MAP':'CARBON FLOW',w/2,h-117,8,'#dce6c1',600,'center');}
      if(p.toast&&p.screen==='play'){const width=Math.min(w-40,Math.max(250,p.toast.length*5.7));if(narrow){const y=Math.max(260,h*.28);panel(w/2-width/2,y,width,64,.92);wrap(p.toast,w/2-width/2+14,y+21,width-28,9,'#ecedcf',16);}else{panel(w/2-width/2,h*.23,width,43,.92);text(p.toast,w/2,h*.23+26,11,'#ecedcf',450,'center');}}
      const ended=s.status!=='active'&&p.screen==='play';
      if(p.screen!=='play'||ended){ctx.fillStyle='rgba(13,30,22,.77)';ctx.fillRect(0,0,w,h);const cx=w/2,cy=h/2;
        if(p.screen==='brief'){text('V E R D A N T',cx,cy-158,12,'#b9cda0',650,'center');text(level.title,cx,cy-101,narrow?32:46,'#f0efd7',500,'center');text(m.latin,cx,cy-72,12,'#a9c291',400,'center');wrap(m.description,cx-Math.min(250,w/2-30),cy-25,Math.min(500,w-60),13,'#bdceaa',23);text(`Grow to ${m.target} g  ·  Vitality ≥ 75%  ·  Connect ${level.roots} soil patches`,cx,cy+70,narrow?10:13,'#ebdfb1',500,'center');text(`${m.days} days  /  €${m.budget} research grant  /  ${m.water} L water`,cx,cy+99,11,'#a8be90',400,'center');text('ENTER THE GREENHOUSE',cx,cy+161,12,'#e9edcd',600,'center');text('Press Enter or click to begin',cx,cy+188,10,'#a5bd8e',400,'center');text('Guide roots with WASD or click soil. Branch with B. Tools: 1–6. Pause: P.',cx,h-35,narrow?7:10,'#8fa97b',400,'center');}
        else if(ended){text(p.complete?'SPECIMEN ESTABLISHED':'EXPERIMENT ENDED',cx,cy-88,11,p.complete?'#b9d69a':'#d6b393',600,'center');text(p.complete?(nextLevel(level.id)?'Life finds a way.':'The station is flourishing.'):'Try another approach.',cx,cy-31,narrow?30:43,'#eeeed4',500,'center');text(`${s.biomass.toFixed(2)} g biomass   ·   ${s.health.toFixed(0)}% vitality   ·   ${p.world.connections} connected patches`,cx,cy+14,narrow?10:13,'#bbcca5',400,'center');text(p.complete?(nextLevel(level.id)?`${'★'.repeat(p.session.result?.stars??1)}  ·  Enter for the next assignment`:'Six habitats completed. M to replay for three stars.'):'Press R or click to retry with a fresh grant',cx,cy+79,12,'#eadcb1',500,'center');text(p.complete?'J  Review observations   ·   H  Read the science':p.session.result?.reasons[0]??'J  Review observations',cx,cy+114,10,'#93af7c',400,'center');}
        else if(p.screen==='pause'){text('THE GREENHOUSE CAN WAIT.',cx,cy-83,11,'#b0c796',600,'center');text('Take a breath.',cx,cy-23,narrow?36:52,'#f0efd7',500,'center');text('P  Resume    E  Equipment    M  Assignments',cx,cy+40,12,'#bdd2a2',400,'center');text('H  Field guide    J  Journal    R  Restart',cx,cy+74,12,'#bdd2a2',400,'center');text('F9  Export checkpoint    F10  Resume checkpoint',cx,cy+110,10,'#a0b78c',400,'center');text('Press Escape or click below to return',cx,cy+157,10,'#91ad7b',400,'center');}
        else if(p.screen==='equipment'){text('RESEARCH EQUIPMENT',cx,cy-219,11,'#b8cfa1',600,'center');text(`€${s.budget} remaining`,cx,cy-189,15,'#f0e3b9',500,'center');const ew=Math.min(560,w-40),ex=cx-ew/2,ey=cy-165;equipmentInfo.forEach((e,i)=>{const y=ey+i*82,owned=s.equipment.includes(e.id);panel(ex,y,ew,74,.75);text(`${i+1}`,ex+16,y+28,10,'#b7ce9b',600);text(e.name,ex+44,y+27,14,'#e9edce',500);wrap(e.description,ex+44,y+47,ew-140,9,'#9fb78a',15);text(owned?'INSTALLED':`€${e.price}`,ex+ew-16,y+29,11,owned?'#9eba83':'#e1cca0',500,'right');});text('Press 1–4 to buy. Escape to return.',cx,cy+211,10,'#a2bd8b',400,'center');}
        else if(p.screen==='missions'){
          text('THE RESEARCH CAMPAIGN',cx,Math.max(40,(h-Math.min(400,h-200))/2-50),11,'#b6cba0',600,'center');
          text('Six habitats. Six living challenges.',cx,Math.max(70,(h-Math.min(400,h-200))/2-17),narrow?21:28,'#eeedcf',500,'center');
          missionCells(w,h).forEach(cell=>{const l=levels[cell.i],open=unlocked(p.campaign,l.id),stars=p.campaign.best[l.id]??0;panel(cell.x,cell.y,cell.w,cell.h,.82);text(`${l.number} / ${l.species.toUpperCase()}`,cell.x+14,cell.y+24,8,open?'#b9cda0':'#7f9675',550);text(l.title,cell.x+14,cell.y+51,narrow?13:17,open?'#e8eccc':'#8da380',500);wrap(l.lesson,cell.x+14,cell.y+76,cell.w-28,narrow?8:10,open?'#a5bd8e':'#708768',17);text(stars?'★'.repeat(stars):open?`${l.mission.days} days · €${l.mission.budget}`:'Complete the preceding habitat',cell.x+14,cell.y+cell.h-18,9,stars?'#e1c986':'#9bb486',500);});
          text('Press 1–6 to select an unlocked assignment. Escape to return.',cx,h-35,narrow?8:10,'#9db888',400,'center');
        }
        else if(p.screen==='guide'){const gw=Math.min(690,w-50),gx=cx-gw/2;text('FIELD NOTES / THE SCIENCE OF SURVIVAL',gx,cy-224,10,'#b6cba0',600);text('Understand the living system.',gx,cy-183,narrow?22:32,'#eeeecf',500);let y=cy-139;const items=[['01 / LIGHT & CARBON','Light builds carbohydrates from CO₂ and water. Respiration uses those reserves day and night. Root extension costs carbon. Shade saves water but reduces light capture.'],['02 / WATER & ROOTS','Grow roots into moisture patches for gradual uptake. Rock blocks root growth. Waterlogged soil restricts oxygen; wilting can mean too little water or too little root aeration.'],['03 / MINERALS & SALT','Nitrogen supports construction of new tissue. Fertilizer also adds salts, which can restrict water uptake. Carnivorous plants gain mineral nutrients from prey, not their main energy supply.'],['04 / YOUR SPECIMEN',m.fact]];items.forEach(([label,body])=>{text(label,gx,y,9,'#d7dcb9',600);y=wrap(body,gx,y+24,gw,narrow?10:12,'#a9c08f',narrow?17:21)+22;});text('Teaching model: rates are tuned for play; root uptake feeds one mixed soil zone.',gx,y+5,narrow?8:10,'#bba77d');text('Space / Escape to return  ·  Sources & model notes: README.md',cx,h-34,10,'#9fba89',400,'center');}
        else if(p.screen==='journal'){const jw=Math.min(650,w-50),jx=cx-jw/2;text('THE EXPERIMENT RECORD',jx,cy-220,10,'#b6cba0',600);text('Every action leaves evidence.',jx,cy-178,narrow?25:34,'#eeeed0',500);let y=cy-135;s.logs.slice(0,5).forEach(l=>{text(`DAY ${Math.floor(l.time/24)+1} / ${l.title}`,jx,y,11,'#dbe4c0',550);y=wrap(l.text,jx,y+22,jw,narrow?10:11,'#9fb98b',18)+23;});text('Escape to return',cx,h-35,10,'#a3bc8c',400,'center');}
      }
    };draw();return()=>{cancelAnimationFrame(frame);ro.disconnect();};
  },[]);
  return <canvas ref={ref} className="game-hud" aria-label="Game HUD: use WASD to grow roots, B to branch, 1–6 to select tools, P to pause, E for equipment, M for missions, H for science."/>;
}
