export const STATIONS = [
  {
    name: "Ragtime",
    frequency: 600000,
    title: "The Entertainer",
    artist: "Scott Joplin · performed by IE (2007)",
    file: "entertainer.mp3",
    kind: "Piano / 1902 composition",
    source:
      "https://commons.wikimedia.org/wiki/File:The_Entertainer_-_Scott_Joplin.ogg",
    license:
      "Composition public domain; performance dedicated to the public domain by IE.",
  },
  {
    name: "Classics",
    frequency: 750000,
    title: "Hungarian Rhapsody No. 2, part I",
    artist: "Franz Liszt · Sergei Rachmaninoff (1919)",
    file: "rhapsody.mp3",
    kind: "Historic piano / 1919 recording",
    source:
      "https://commons.wikimedia.org/wiki/File:Second_Hungarian_Rhapsody.ogg",
    license:
      "Public-domain Edison recording, sourced from the Library of Congress via Wikimedia Commons.",
  },
  {
    name: "Fireside",
    frequency: 900000,
    title: "The first fireside chat",
    artist: "Franklin D. Roosevelt · 12 March 1933",
    file: "fireside.mp3",
    kind: "Historic spoken radio / 1933",
    source:
      "https://commons.wikimedia.org/wiki/File:Fireside_Chat_1,_On_the_Banking_Crisis_(March_12,_1933),_Franklin_Delano_Roosevelt_second_edit.ogg",
    license:
      "US federal government work; marked public domain by Wikimedia Commons.",
  },
  {
    name: "Bells",
    frequency: 1050000,
    title: "A bell in the air",
    artist: "code4fukui / sound-cc0",
    file: "bell.wav",
    kind: "Sound experiment / CC0",
    source: "https://github.com/code4fukui/sound-cc0",
    license: "Public-domain / CC0 sound collection.",
  },
  {
    name: "Test lab",
    frequency: 1200000,
    title: "1 kHz reference tone",
    artist: "Generated by this simulation",
    file: "",
    kind: "Calibration / sine wave",
    source: "",
    license: "Procedurally generated.",
  },
] as const;
